name: linter

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  php-version: '8.4'
  node-version: '22'
  node-cache: 'npm'

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      # For auto-commit
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: '${{ github.head_ref }}'
          persist-credentials: true

      - name: PHP Setup
        uses: "./.github/actions/php-setup"
        with:
          php-version: ${{ env.php-version }}
          php-extensions: ''
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ env.node-version }}
          cache: ${{ env.node-cache }}

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint
        run: composer lint

      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: github-actions[bot]
          commit_message: fix code style
          commit_options: '--no-verify'
